<div class="footer-links-wrap information" >
  <div class="h4 title">CÔNG TY TNHH ĐIỆN TỬ SHARP VIỆT NAM</div>
</div>
<div class="footer-container">
    <div class="address">Địa chỉ: T5-B03.07 &amp; T5-B03.09, Lầu 3 Masteri Thảo Điền <br>159 Võ Nguyên Giáp, Phường Thảo
      Điền, T.P Thủ Đức, T.P Hồ Chí Minh, Việt Nam</div>
    <div class="email">Email: <a class="text-light" href="mailto:cskh@cocorolife.vn">cskh@cocorolife.vn</a></div>
    <div class="address">MST: 0308159258 Do Sở kế hoạch Đầu tư TP.HCM cấp ngày 13/3/2009</div>
    <a href="http://online.gov.vn/Home/WebDetails/91028" target="_blank" rel="noopener"><img style="max-width: 150px;"
        title="" src="https://www.cocorolife.vn/media/wysiwyg/homepage/logoSaleNoti.png" alt="" width="300"> </a>
  </div>