<div class="footer-links-wrap toggle-mobile">
  <div class="h4 title">Kết nối với chúng tôi<i class="mbi mbi-chevron-down"></i></div>
</div>
<div class="footer-container content-toggle">
  <ul class="social-links d-flex mb-3">
    <li><a class="m-5" title="facebook" href="https://www.facebook.com/cocorolifevietnam/" target="_blank" ><img src="https://www.cocorolife.vn/media/wysiwyg/homepage/Facebook.png" alt="" width="20"><span class="text-hide">Facebook</span></a></li>
    <li><a class="m-3" title="youtube" href="" target="_blank" ><img src="https://www.cocorolife.vn/media/wysiwyg/homepage/Youtube.png" alt="" width="20"><span class="text-hide">Youtube</span></a></li>
  </ul>
  <div style="padding-bottom: 4px;" class="d-flex flex-column">
    <div>
      <img class="img-contact mb-2" src="https://www.cocorolife.vn/media/wysiwyg/homepage/COD_pow.png" alt="" > 
    </div>
    <div>
      <img class="img-contact mb-2"  src="https://www.cocorolife.vn/media/wysiwyg/homepage/ATM_pow.png" alt="" >
    </div>
  </div>
  <div>
    <img class="img-contact"  style="padding-right: 4px;" src="https://www.cocorolife.vn/media/wysiwyg/homepage/VISA_pow.png" alt="" >
    <img class="img-contact"  style="padding-right: 4px;" src="https://www.cocorolife.vn/media/wysiwyg/homepage/Master_pow.png" alt="" ">
    <img class="img-contact"  src="https://www.cocorolife.vn/media/wysiwyg/homepage/JCB_pow.png" alt="" >
  </div>
</div>