<div class="row mt-5 mb-5">
  <div class="col-12 col-xl-8 slider-slick">
    <div class="d-block img-slide"><a href="https://www.cocorolife.vn/vi/promotions/"> <span
          class="img-lazy-wrap lazyloaded-wrap" style="padding-bottom: 44.01%;"><img class="media-lazy lazyloaded "
            src="https://www.cocorolife.vn/media/.renditions/wysiwyg/banner/Oct2023/W1_pc_vn.jpg" alt="" width="1920"
            height="845"
            data-src="https://www.cocorolife.vn/media/.renditions/wysiwyg/banner/Oct2023/W1_pc_vn.jpg"></span> </a>
    </div>
    <div class="d-block img-slide"><a href="https://www.cocorolife.vn/vi/promotions/"> <span
          class="img-lazy-wrap lazyloaded-wrap" style="padding-bottom: 44.01%;"><img class="media-lazy lazyloaded "
            src="https://www.cocorolife.vn/media/.renditions/wysiwyg/banner/Oct2023/W1_pc_vn.jpg" alt="" width="1920"
            height="845"
            data-src="https://www.cocorolife.vn/media/.renditions/wysiwyg/banner/Oct2023/W1_pc_vn.jpg"></span> </a>
    </div>
    <div class="d-block img-slide"><a href="https://www.cocorolife.vn/vi/promotions/"> <span
          class="img-lazy-wrap lazyloaded-wrap" style="padding-bottom: 44.01%;"><img class="media-lazy lazyloaded "
            src="https://www.cocorolife.vn/media/.renditions/wysiwyg/banner/Oct2023/W1_pc_vn.jpg" alt="" width="1920"
            height="845"
            data-src="https://www.cocorolife.vn/media/.renditions/wysiwyg/banner/Oct2023/W1_pc_vn.jpg"></span> </a>
    </div>
    <div class="d-block img-slide"><a href="https://www.cocorolife.vn/vi/promotions/"> <span
          class="img-lazy-wrap lazyloaded-wrap" style="padding-bottom: 44.01%;"><img class="media-lazy lazyloaded "
            src="https://www.cocorolife.vn/media/.renditions/wysiwyg/banner/Oct2023/W1_pc_vn.jpg" alt="" width="1920"
            height="845"
            data-src="https://www.cocorolife.vn/media/.renditions/wysiwyg/banner/Oct2023/W1_pc_vn.jpg"></span> </a>
    </div>
  </div>
  <div class="col-12 col-xl-4">
    <div class="row h-100">
      <div class="col-6 col-md-6 col-xl-12   pt-2">
        <div class="h-100 d-flex justify-content-start">
          <img class="media-lazy lazyloaded "
            src="https://www.cocorolife.vn/media/.renditions/wysiwyg/homepage/banner_2_Ch_o_m_ng_th_nh_vi_n_m_i_.png"
            alt="" height="100%">
        </div>
      </div>
      <div class="col-6 col-md-6 col-xl-12  pt-2">
        <div class="h-100 d-flex justify-content-end">
          <img class="media-lazy lazyloaded "
            src="https://www.cocorolife.vn/media/.renditions/wysiwyg/homepage/banner_3_gi_m_s_u_th_4_vi_t_.jpg" alt=""
            height="100%">
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row mt-5 mb-5">
  <div class="col-12">
    <div class="row">
      <div class="col-6 col-lg-3 d-flex align-items-center">
        <div class="d-flex justify-content-center align-items-center">
          <div class=""><img src="https://www.cocorolife.vn/media//wysiwyg/homepage/Giao_h_ng_mi_n_ph_1_.png" alt=""
              width="80"></div>
          <div class="d-flex flex-column">
            <div class="media-heading">Giao Hàng Miễn Phí</div>
            <div class="text-desc">Cho đơn hàng hơn 2,000,000đ<br></div>
          </div>

        </div>
        <hr class="d-none d-xl-block hr-vertical">
      </div>

      <div class="col-6 col-lg-3 d-flex align-items-center">
        <div class="d-flex align-items-center justify-content-center">
          <div class=""><img src="https://www.cocorolife.vn/media//wysiwyg/homepage/H_ng_ch_nh_h_ng_1_.png" alt=""
              width="80"></div>
          <div class="d-flex flex-column">
            <div class="media-heading">Hàng Chính Hãng</div>
            <div class="text-desc">Xuất xứ rõ ràng<br></div>
          </div>

        </div>
        <hr class="hr-vertical d-none d-xl-block ">
      </div>

      <div class="col-6 col-lg-3 d-flex align-items-center">
        <div class="d-flex align-items-center justify-content-center">
          <div class=""><img src="https://www.cocorolife.vn/media//wysiwyg/homepage/Thanh_to_n_an_to_n_1_.png" alt=""
              width="80"></div>
          <div class="d-flex flex-column">
            <div class="media-heading">Thanh toán an toàn</div>
            <div class="text-desc">Tiền mặt và Thẻ<br> Hỗ trợ trả góp qua thẻ</div>
          </div>

        </div>
        <hr class="hr-vertical d-none d-xl-block ">
      </div>

      <div class="col-6 col-lg-3 d-flex align-items-center">
        <div class="d-flex align-items-center">
          <div class=""><img src="https://www.cocorolife.vn/media//wysiwyg/homepage/CSKH_1_.png" alt="" width="80">
          </div>
          <div class="d-flex flex-column">
            <div class="media-heading">Tổng Đài CSKH</div>
            <div class="text-desc">9:00 - 18:00<br>Thứ 2 - Thứ 6</div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-12 mt-5">
    <hr>
  </div>
</div>

<div class="block-static clearfix">
  <div class="main-heading">
    <h2 class="heading-title mt-5 mb-5"><span>Danh mục hàng đầu trong tháng</span></h2>
  </div>
  <div data-content-type="html" data-appearance="default" data-element="main" data-decoded="true">
    <div class="row">
      <div class="mb-2 col-12 col-sm-6 col-xl-4 top-category"><a href="/audio-visual.html"><img
            style="width: 100%; border-radius: 10px; border: 1px solid #b8b8b8;"
            src="https://www.cocorolife.vn/media//wysiwyg/homepage/Thi_t_b_nghe_nh_n_copy_1_.png" height=""></a></div>
      <div class="mb-2 col-12 col-sm-6 col-xl-4 top-category"><a href="/small-home-appliances.html"><img
            style="width: 100%; border-radius: 10px; border: 1px solid #b8b8b8;"
            src="https://www.cocorolife.vn/media//wysiwyg/homepage/Thi_t_b_nh_b_p_copy_1_.png"></a></div>
      <div class="mb-2 col-12 col-sm-6 col-xl-4 top-category"><a href="/home-appliances.html"><img
            style="width: 100%; border-radius: 10px; border: 1px solid #b8b8b8;"
            src="https://www.cocorolife.vn/media//wysiwyg/homepage/Thi_t_b_gia_d_ng_copy_1_.png"></a></div>
      <div class="mb-2 col-12 col-sm-6 col-xl-4 top-category"><a href="/accessories.html"><img
            style="width: 100%; border-radius: 10px; border: 1px solid #b8b8b8;"
            src="https://www.cocorolife.vn/media//wysiwyg/homepage/Ph_ki_n_sharp_ch_nh_h_ng.png" height=""></a></div>
      <div class="mb-2 col-12 col-sm-6 col-xl-4 top-category"><a href="/cosmetics.html"><img
            style="width: 100%; border-radius: 10px; border: 1px solid #b8b8b8;"
            src="https://www.cocorolife.vn/media//wysiwyg/homepage/M_ph_m.png"></a></div>
      <div class="mb-2 col-12 col-sm-6 col-xl-4 top-category"><a href="/thuc-pham-chuc-nang.html"><img
            style="width: 100%; border-radius: 10px; border: 1px solid #b8b8b8;"
            src="https://www.cocorolife.vn/media//wysiwyg/homepage/Th_c_ph_m_ch_c_n_ng.png"></a></div>
    </div>
  </div>
</div>

<div id="element">
    <div data-role="collapsible" >
        <div data-role="trigger">
            <h3>Title 1</h3>
        </div>
    </div>
    <div data-role="content" >Content 1</div>

    <div data-role="collapsible" >
        <div data-role="trigger">
            <h3>Title 2</h3>
        </div>
    </div>
    <div data-role="content">Content 2</div>

    <div data-role="collapsible" >
        <div data-role="trigger">
            <h3>Title 3</h3>
        </div>
    </div>
    <div data-role="content">Content 3</div>
</div>

<!-- <div id="accordion" data-mage-init='{
        "accordion":{
            "active": [0],
            "collapsible": true,
            "openedState": "active",
            "multipleCollapsible": true
        }}'>
    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>Title 1</h4>
        </div>
    </div>
    <div data-role="content">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>Title 2</h4>
        </div>
    </div>
    <div data-role="content"> It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>Title 3</h4>
        </div>
    </div>
    <div data-role="content">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</div>
</div> -->


<script>
   require([
      'jquery',
      'slick',
      'accordion',
      'domReady!'
   ], function ($) {
      $(".slider-slick").slick({
        dots: false,
        infinite: true,
        speed: 300,
        slidesToShow: 1,
        slidesToScroll: 1,
        autoplay: true,
        autoplaySpeed: 2000,
      });
      
      $("#element").accordion({ 
            "active": [0],
            "collapsible": true,
            "openedState": "active",
            "multipleCollapsible": true });


   });
</script>


