<div class="group-sale-price">
  <div class="price-title d-flex align-items-center">
    <div class="icon">
      <img class="mr-2"
        src="https://www.cocorolife.vn/static/version1697640168/frontend/MageBig/martfury_layout02/vi_VN/Cocoro_ProductPricing/images/member.svg"
        alt="member icon">
    </div>
    <div class="price-name">Giá Thành Viên</div>
  </div>
  <div class="group-sale-price">
    <div class="price-container">
      <div class="old-price price text-secondary"><s>809,000 ₫</s></div>
    </div>
  </div>
</div>