<div id="custom-form-container" class="w-50" data-bind="scope: 'custom-form'">
    <h2><?= __('Form contact'); ?></h2>
    <!-- UI Component form -->
    <form data-bind="submit: onSubmit" class="form" id="custom-form">
        <div class="field">
            <label for="name"><?php echo __('Name'); ?></label>
            <input type="text" id="name" name="name" data-bind="value: formData().name">
            <div class="text-danger" id="custom-form-message" data-bind="text: messageName, visible: showMessageName"></div>
        </div>
        <div class="field">
            <label for="email"><?php echo __('Email'); ?></label>
            <input type="text" id="email" name="email" data-bind="value: formData().email">
            <div class="text-danger" id="custom-form-message" data-bind="text: messageEmail, visible: showMessageEmail"></div>
        </div>
        <div class="field">
            <label for="message"><?php echo __('Message'); ?></label>
            <textarea id="message" name="message" data-bind="value: formData().message"></textarea>
            <div class="text-danger" id="custom-form-message" data-bind="text: messageMess, visible: showMessageMess"></div>
        </div>
        <button type="submit"><?php echo __('Submit'); ?></button>
    </form>
</div>

<script type="text/x-magento-init">
    {
        "#custom-form-container": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "custom-form": {
                        "component": "Magento_Catalog/js/custom-form"
                    }
                }
            }
        }
    }
</script>
